name: easy_events
version: 0.0.1
author: movinliao <movinliao@163.com>
description: A easy events
repository: https://github.com/movins/easy-events
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  analyzer: any
  build: any
  source_gen: '>=0.8.0'
  build_config: '>=0.3.0'
  mustache4dart: any
dev_dependencies:
  build_runner: ^1.2.5
  build_test: ^0.10.3
  logging: ^0.11.0
  test: ^1.5.0
